worker_processes 1;

error_log /tmp/cn-nginx-error.log notice;
pid /tmp/cn-nginx.pid;

events {
    worker_connections 128;
}

http {
    default_type application/octet-stream;

    access_log /tmp/cn-nginx-access.log;

    upstream backend_pool {
        # Round-robin is the default nginx load-balancing method.
        server 10.253.140.203:3001;
        server 10.253.140.1:3002;
    }

    server {
    listen 10.253.140.31:8443 ssl;
    server_name app.team1.test api.team1.test;

    ssl_certificate /Users/anandmishra1/cn-private-network-platform/config/tls/team1-server.crt;
    ssl_certificate_key /Users/anandmishra1/cn-private-network-platform/config/tls/team1-server.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://backend_pool;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
}
