port=53
listen-address=10.253.140.169
bind-interfaces

domain-needed
bogus-priv
server=8.8.8.8
address=/app.team1.test/10.253.140.31
address=/api.team1.test/10.253.140.31

local-ttl=30

log-queries
log-facility=/tmp/cn-dnsmasq.log

pid-file=/tmp/cn-dnsmasq.pid
